### ISSUE TITLE
Native Mac Window

### ISSUE THREAD

**Issue by musgravejw** [domfarolino/browser#14]
After some brief Googling it looks like it's pretty straightforward to include the Cocoa header for the MacOS API.

https://developer.apple.com/documentation/objectivec/objective-c_runtime
https://stackoverflow.com/questions/30269329/creating-window-application-in-pure-c-on-mac-osx
https://github.com/richardjrossiii/CBasediOSApp

So, this is not a lot of code.  I ran the example and it worked.  But, they were compiling for Cocoa with GCC, and I'm not sure how this will work with our compilation step.  There is probably a way to import the library via Bazel.

**Comment by domfarolino** [comment]
@musgravejw What do you think the status of this issue is? Do you think that we should close it in favor of figuring out how to integrate with SDL2, instead of platform-specific windowing things? Not sure what we roughly resolved on last...

**Comment by musgravejw** [comment]
Yeah, I'm totally fine with closing.  Either way is fine.  This opens a native window, but the integration was getting kind of awkward.
